/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class re2dfa_MainPage */

#ifndef _Included_re2dfa_MainPage
#define _Included_re2dfa_MainPage
#ifdef __cplusplus
extern "C" {
#endif
#undef re2dfa_MainPage_FOCUS_TRAVERSABLE_UNKNOWN
#define re2dfa_MainPage_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef re2dfa_MainPage_FOCUS_TRAVERSABLE_DEFAULT
#define re2dfa_MainPage_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef re2dfa_MainPage_FOCUS_TRAVERSABLE_SET
#define re2dfa_MainPage_FOCUS_TRAVERSABLE_SET 2L
#undef re2dfa_MainPage_TOP_ALIGNMENT
#define re2dfa_MainPage_TOP_ALIGNMENT 0.0f
#undef re2dfa_MainPage_CENTER_ALIGNMENT
#define re2dfa_MainPage_CENTER_ALIGNMENT 0.5f
#undef re2dfa_MainPage_BOTTOM_ALIGNMENT
#define re2dfa_MainPage_BOTTOM_ALIGNMENT 1.0f
#undef re2dfa_MainPage_LEFT_ALIGNMENT
#define re2dfa_MainPage_LEFT_ALIGNMENT 0.0f
#undef re2dfa_MainPage_RIGHT_ALIGNMENT
#define re2dfa_MainPage_RIGHT_ALIGNMENT 1.0f
#undef re2dfa_MainPage_serialVersionUID
#define re2dfa_MainPage_serialVersionUID -7644114512714619750i64
#undef re2dfa_MainPage_serialVersionUID
#define re2dfa_MainPage_serialVersionUID 4613797578919906343i64
#undef re2dfa_MainPage_INCLUDE_SELF
#define re2dfa_MainPage_INCLUDE_SELF 1L
#undef re2dfa_MainPage_SEARCH_HEAVYWEIGHTS
#define re2dfa_MainPage_SEARCH_HEAVYWEIGHTS 1L
#undef re2dfa_MainPage_OPENED
#define re2dfa_MainPage_OPENED 1L
#undef re2dfa_MainPage_serialVersionUID
#define re2dfa_MainPage_serialVersionUID 4497834738069338734i64
#undef re2dfa_MainPage_DEFAULT_CURSOR
#define re2dfa_MainPage_DEFAULT_CURSOR 0L
#undef re2dfa_MainPage_CROSSHAIR_CURSOR
#define re2dfa_MainPage_CROSSHAIR_CURSOR 1L
#undef re2dfa_MainPage_TEXT_CURSOR
#define re2dfa_MainPage_TEXT_CURSOR 2L
#undef re2dfa_MainPage_WAIT_CURSOR
#define re2dfa_MainPage_WAIT_CURSOR 3L
#undef re2dfa_MainPage_SW_RESIZE_CURSOR
#define re2dfa_MainPage_SW_RESIZE_CURSOR 4L
#undef re2dfa_MainPage_SE_RESIZE_CURSOR
#define re2dfa_MainPage_SE_RESIZE_CURSOR 5L
#undef re2dfa_MainPage_NW_RESIZE_CURSOR
#define re2dfa_MainPage_NW_RESIZE_CURSOR 6L
#undef re2dfa_MainPage_NE_RESIZE_CURSOR
#define re2dfa_MainPage_NE_RESIZE_CURSOR 7L
#undef re2dfa_MainPage_N_RESIZE_CURSOR
#define re2dfa_MainPage_N_RESIZE_CURSOR 8L
#undef re2dfa_MainPage_S_RESIZE_CURSOR
#define re2dfa_MainPage_S_RESIZE_CURSOR 9L
#undef re2dfa_MainPage_W_RESIZE_CURSOR
#define re2dfa_MainPage_W_RESIZE_CURSOR 10L
#undef re2dfa_MainPage_E_RESIZE_CURSOR
#define re2dfa_MainPage_E_RESIZE_CURSOR 11L
#undef re2dfa_MainPage_HAND_CURSOR
#define re2dfa_MainPage_HAND_CURSOR 12L
#undef re2dfa_MainPage_MOVE_CURSOR
#define re2dfa_MainPage_MOVE_CURSOR 13L
#undef re2dfa_MainPage_NORMAL
#define re2dfa_MainPage_NORMAL 0L
#undef re2dfa_MainPage_ICONIFIED
#define re2dfa_MainPage_ICONIFIED 1L
#undef re2dfa_MainPage_MAXIMIZED_HORIZ
#define re2dfa_MainPage_MAXIMIZED_HORIZ 2L
#undef re2dfa_MainPage_MAXIMIZED_VERT
#define re2dfa_MainPage_MAXIMIZED_VERT 4L
#undef re2dfa_MainPage_MAXIMIZED_BOTH
#define re2dfa_MainPage_MAXIMIZED_BOTH 6L
#undef re2dfa_MainPage_serialVersionUID
#define re2dfa_MainPage_serialVersionUID 2673458971256075116i64
#undef re2dfa_MainPage_serialVersionUID
#define re2dfa_MainPage_serialVersionUID -5146281710032081675i64
/*
 * Class:     re2dfa_MainPage
 * Method:    getRowofNFA
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_re2dfa_MainPage_getRowofNFA
  (JNIEnv *, jobject);

/*
 * Class:     re2dfa_MainPage
 * Method:    getRowofDFA
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_re2dfa_MainPage_getRowofDFA
  (JNIEnv *, jobject);

/*
 * Class:     re2dfa_MainPage
 * Method:    getRowofMDFA
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_re2dfa_MainPage_getRowofMDFA
  (JNIEnv *, jobject);

/*
 * Class:     re2dfa_MainPage
 * Method:    getEpsilon
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_re2dfa_MainPage_getEpsilon
  (JNIEnv *, jobject, jint);

/*
 * Class:     re2dfa_MainPage
 * Method:    getGroupofDFA
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_re2dfa_MainPage_getGroupofDFA
  (JNIEnv *, jobject, jint);

/*
 * Class:     re2dfa_MainPage
 * Method:    getGroupofMDFA
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_re2dfa_MainPage_getGroupofMDFA
  (JNIEnv *, jobject, jint);

/*
 * Class:     re2dfa_MainPage
 * Method:    getNFA
 * Signature: ()[[I
 */
JNIEXPORT jobjectArray JNICALL Java_re2dfa_MainPage_getNFA
  (JNIEnv *, jobject);

/*
 * Class:     re2dfa_MainPage
 * Method:    getDFA
 * Signature: ()[[I
 */
JNIEXPORT jobjectArray JNICALL Java_re2dfa_MainPage_getDFA
  (JNIEnv *, jobject);

/*
 * Class:     re2dfa_MainPage
 * Method:    getMinDFA
 * Signature: ()[[I
 */
JNIEXPORT jobjectArray JNICALL Java_re2dfa_MainPage_getMinDFA
  (JNIEnv *, jobject);

/*
 * Class:     re2dfa_MainPage
 * Method:    addCharSet
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_re2dfa_MainPage_addCharSet
  (JNIEnv *, jobject, jstring);

/*
 * Class:     re2dfa_MainPage
 * Method:    GetCharSet
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_re2dfa_MainPage_GetCharSet
  (JNIEnv *, jobject);

/*
 * Class:     re2dfa_MainPage
 * Method:    buildFA
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_re2dfa_MainPage_buildFA
  (JNIEnv *, jobject, jstring);

/*
 * Class:     re2dfa_MainPage
 * Method:    ShowPicture
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_re2dfa_MainPage_ShowPicture
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
